matrix:
  include:
  - language: python
    name: "ui-server"
    python: "3.6"
    before_install:
    - cd server-ui
    install:
    - pip install requirements.txt

  - language: node_js
    name: "client-ui"
    node_js:
    - "node"
    branches:
      except:
      - gh-pages
    cache:
      directories:
      - node_modules
    before_install:
    - cd ui
    install:
    - npm install @angular/cli
      npm install
    script:
    - ng build --prod
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
        branch: master
      local_dir: dist/controlpanel
