matrix:
  include:
  - language: python
    name: "ui-server"
    python: "3.6"

  - language: node_js
    name: "client-ui"
    node_js:
    - "node"
    dist: trusty
    sudo: false

    branches:
      except:
      - gh-pages

    cache:
      directories:
      - node_modules

    before_script:
    - npm install @angular/cli
      npm install

    script:
    - ng build --prod

    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
        branch: master
      local_dir: dist/controlpanel
